sudo: required

language: python

python:
  - 2.7

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.10.0

install: sudo pip install -r requirements.txt -t app/vendors

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod a+x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose up -d

script: docker-compose exec web tools/all_tests

